### ISSUE TITLE
Add Contributor Byline on Articles

### ISSUE THREAD

**Issue by bmartinez287** [ddev/ddev.com#126]
To encourage and promote contributed articles. We should add that byline Randy was talking about a while back. 
It provides visible contribution credit for those adding blogs to the site.
Contributor is technically the correct term but Added by sounds nicer and more modern. Thoughts?
I'm good with either.
I also thought of Editor or Patron or other terms, but those don't fit in some cases. Like there might be multiple editors, but only one contributor since that person created said PR.

![contributorimage](https://github.com/ddev/ddev.com/assets/39039024/f83f9c0a-49c2-4761-88a5-1e17513540ee)
![addedby](https://github.com/ddev/ddev.com/assets/39039024/4f27517b-2978-4bbf-a564-154897dd3f97)

**Comment by bmartinez287** [comment]
@rfay @mattstein thoughts on this?

**Comment by rfay** [comment]
I would think "author" would be the right thing for the actual author. I guess you're saying "contributor" for someone who packages up another author's work? Sounds OK to me. "Editor" would be good as well. We can also make sure to do this manually and it's OK with me.

**Comment by bmartinez287** [comment]
Yeah author would be left to the original creator of the source of information as well as, in cases were it was heavily inspired by someone else recording or work that would then.

An Editor tag could work too, but an article can have multiple editors including Matt and yourself as different ideas come in. We could make it editor if that's preferred, but it could be more confusing than Added by or Contributor which directly refers to the person who added the article to the repo. Either way, the main goal is to give credit to those adding the articles. @mattstein  do you have a preference?

**Comment by bmartinez287** [comment]
For example, the front matter would go from this 
```
title: "ARM64! Apple Silicon! M1! DDEV! What does it all mean?"
pubDate: 2020-11-18
summary: A look at Apple’s new chip architecture and what it means for DDEV.
modifiedDate: 2023-03-12
modifiedComment: "We’ve updated this post to reflect the continued support for Apple silicon since it was first published."
author: Randy Fay
featureImage:
  src: /img/blog/2020/11/apple-ddev.jpg
  alt: Apple M1 logo and DDEV logo side by side
categories:
  - DevOps
  - Performance
```

to this 

```
title: "ARM64! Apple Silicon! M1! DDEV! What does it all mean?"
pubDate: 2020-11-18
summary: A look at Apple’s new chip architecture and what it means for DDEV.
modifiedDate: 2023-03-12
modifiedComment: "We’ve updated this post to reflect the continued support for Apple silicon since it was first published."
author: Randy Fay
editor: John Doe
featureImage:
  src: /img/blog/2020/11/apple-ddev.jpg
  alt: Apple M1 logo and DDEV logo side by side
categories:
  - DevOps
  - Performance
```
